language: node_js

node_js:
  - node
  - lts/*

env:
  global:
    - CC_TEST_REPORTER_ID=349f02fef2918c1f71d869a67be039003392207917ac4e8431c0d8988bcfc7bb

before_script:
  - wget -O ./cctr https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  - chmod +x ./cctr
  - ./cctr before-build

after_script:
  - ./cctr after-build -t lcov --exit-code $TRAVIS_TEST_RESULT

jobs:
  include:
    - stage: deploy
      script: npm pack
      deploy:
        - provider: npm
          email: me@mgsisk.com
          api_key:
            secure: Dv1rTULMpRtlsb4ATGbwGo/Gy3AJKU/5q67z8NaLyu0OlaVOcU5DwqBB5KZKObUC6MjM8paCvfH1+fQ5T8pGDqvwD2eT3FPU/gGoaM3/Cw8vfPAR//oh1a4hbRYt0cYllCg8KP2omatN6O1oO6WotRQetVN2wHTIK6nsGl/GGZw0nECnsvZaP36FQieXcxOmaO/HEXMAdN+lAlb/QA5R/Ub6gU5X5t+slO91z/q7K1PXFHuz+c6umym5pEuCs4XEWLj/CS0s5LWST2brQaFRQ4RTkg8zLpUXO5pTNoQgDIjOWjfw9wdPcWQ61tQY4Eh36Qwo5ouJQd62qsNVtZ2wmA0S3abIFPQ07bgV0j64djV/w4HRHMYLnjQdSwuL/YQQakxBIABTamoXWnzppetEVDJABcpSjN7TJfFM+c6jSdS3GLmmK98XMzTNIIzwv75fCBq9uUJZNid4OUsZIpLgudKGwp/g/UKl1Uxp1YHMic8lTEZ3RWMFZYlOjcncO2ZC5pr9qD5uzkNTf2DQvefg/dwZ/eoxaDjT+arbeCCGMDMVatoBHRhk7NvvNmCtXjRDHLiPNPSxzbJxEzDLPw1GKxXkswTdl0XqZrhJW61eIkCFJywTlCnSC2yzg/3DpWh5AFnvxX/uUn64xN/kz9le9s0WlND96snjJEQP+ddVx9E=
          on:
            repo: mgsisk/stylelint-config
            tags: true
        - provider: npm
          registry: https://npm.pkg.github.com
          email: me@mgsisk.com
          api_key:
            secure: MIplfCLt6RW7RThHGQAC5ANl7vMAJPrzGQML8cW2usdnvKss8K5QsgGONDy2MU15T88efKaZP7vq7/1N0EAP8dDeLw5U+n2WVWeMr++V9wKV0Rb+HUT3UtkSkHEYsDJ0CY+M65M8tF4dIqUB0SyZjdkjcxjj5Os15WVz2PfsOkXjbpOjYn68Nsoob5f4//WIjk/8E28gSCxJeq0GuSAPVByXae1HjarXoCktrfdubmJ6rzWV+gt6uAhdurJBrtNNJ8mjBH7gIxpvT309cAhehhfrUfxH5tK5nqRd+85PWkaFLUV5fwPfTZ7dmFjoFFxlKlK+iqsNKtaKswz3/FkGB9Dpf4uZQ7erIdpaVv0ZKuajayKzo2dhfMa30/kznnVFmvK/bxdz1iYuaZkdBi+DZr43a9xlYcQ64J4/aQ6PHWpI4XIOOV+zgjojOo8BX+jCXBT81BjQ4MaFfA0hKr64XmVf+H27u1mAJMbSj9Uftxhf3uBSdzOswU4BF3uPOt+y8c+HUgmbriw6KSZ9PvzT8TPuOWNQHfxskznZoODB7hegT+oPxBtyJ+8olPatBdvaDWE7jS8Bt5nrdVcl0rmbJ6iXH7syzYfgrVz+1QrismKCG2ykRk+iQpsfFbtBEXhiMEMdGlH/moM6hr0CmV5GdUnMvjh6IhHDhE+8OG6XFUI=
          edge:
            branch: master
          on:
            repo: mgsisk/stylelint-config
            tags: true
        - provider: releases
          skip_cleanup: true
          file_glob: true
          file: mgsisk-stylelint-config-*.tgz
          api_key:
            secure: MIplfCLt6RW7RThHGQAC5ANl7vMAJPrzGQML8cW2usdnvKss8K5QsgGONDy2MU15T88efKaZP7vq7/1N0EAP8dDeLw5U+n2WVWeMr++V9wKV0Rb+HUT3UtkSkHEYsDJ0CY+M65M8tF4dIqUB0SyZjdkjcxjj5Os15WVz2PfsOkXjbpOjYn68Nsoob5f4//WIjk/8E28gSCxJeq0GuSAPVByXae1HjarXoCktrfdubmJ6rzWV+gt6uAhdurJBrtNNJ8mjBH7gIxpvT309cAhehhfrUfxH5tK5nqRd+85PWkaFLUV5fwPfTZ7dmFjoFFxlKlK+iqsNKtaKswz3/FkGB9Dpf4uZQ7erIdpaVv0ZKuajayKzo2dhfMa30/kznnVFmvK/bxdz1iYuaZkdBi+DZr43a9xlYcQ64J4/aQ6PHWpI4XIOOV+zgjojOo8BX+jCXBT81BjQ4MaFfA0hKr64XmVf+H27u1mAJMbSj9Uftxhf3uBSdzOswU4BF3uPOt+y8c+HUgmbriw6KSZ9PvzT8TPuOWNQHfxskznZoODB7hegT+oPxBtyJ+8olPatBdvaDWE7jS8Bt5nrdVcl0rmbJ6iXH7syzYfgrVz+1QrismKCG2ykRk+iQpsfFbtBEXhiMEMdGlH/moM6hr0CmV5GdUnMvjh6IhHDhE+8OG6XFUI=
          on:
            repo: mgsisk/stylelint-config
            tags: true
