/**
 * Stylelint configuration for general development.
 *
 * @type {object}
 */
module.exports = {
  plugins: [
    'stylelint-declaration-block-no-ignored-properties',
    'stylelint-order',
    'stylelint-use-nesting',
  ],
  extends: ['stylelint-config-standard'],
  rules: {
    // ----- Possible Errors ---------------------------------------------------
    'block-no-empty': null,
    'font-family-no-missing-generic-family-keyword': [true, {ignoreFontFamilies: [/\d+(mfs|mlh|msu|vru)/u]}],
    'property-no-unknown': [true, {ignoreProperties: ['max-size', 'min-size', 'size']}],
    'unit-no-unknown': [true, {ignoreUnits: ['mfs', 'mlh', 'msu', 'vru']}],

    // ----- Limit Language Features -------------------------------------------
    'alpha-value-notation': 'number',
    // 'at-rule-allowed-list': [],
    // 'at-rule-disallowed-list': [],
    'at-rule-no-vendor-prefix': true,
    // 'at-rule-property-required-list': [],
    'color-function-notation': 'modern',
    'color-named': 'always-where-possible',
    // 'color-no-hex': true,
    // 'comment-word-disallowed-list': [],
    // 'custom-media-pattern': '',
    // 'custom-property-pattern': '',
    'declaration-block-no-redundant-longhand-properties': true,
    'declaration-no-important': true,
    // 'declaration-property-unit-allowed-list': [],
    // 'declaration-property-unit-disallowed-list': [],
    // 'declaration-property-value-allowed-list': [],
    // 'declaration-property-value-disallowed-list': [],
    // 'function-allowed-list': [],
    // 'function-disallowed-list': [],
    // 'function-url-scheme-allowed-list': [],
    // 'function-url-scheme-disallowed-list:': [],
    'function-url-no-scheme-relative': true,
    // 'keyframes-name-pattern': '',
    'max-nesting-depth': 8,
    // 'media-feature-name-allowed-list': [],
    // 'media-feature-name-disallowed-list': [],
    'media-feature-name-no-vendor-prefix': true,
    'no-unknown-animations': true,
    'number-max-precision': 5,
    // 'property-allowed-list': [],
    // 'property-disallowed-list': [],
    'property-no-vendor-prefix': true,
    // 'selector-attribute-operator-allowed-list': [],
    // 'selector-attribute-operator-disallowed-list': [],
    // 'selector-class-pattern': '',
    // 'selector-combinator-allowed-list': [],
    // 'selector-combinator-disallowed-list': [],
    // 'selector-id-pattern': '',
    'selector-max-attribute': 4,
    'selector-max-class': 4,
    'selector-max-combinators': 8,
    'selector-max-compound-selectors': 4,
    'selector-max-id': 1,
    'selector-max-pseudo-class': 4,
    'selector-max-specificity': '1,4,4',
    'selector-max-type': 4,
    'selector-max-universal': 1,
    'selector-nested-pattern': '^&.+',
    // 'selector-no-qualifying-type': true,
    'selector-no-vendor-prefix': true,
    // 'selector-pseudo-class-allowed-list': [],
    // 'selector-pseudo-class-disallowed-list': [],
    // 'selector-pseudo-element-allowed-list': [],
    // 'selector-pseudo-element-disallowed-list': [],
    'shorthand-property-no-redundant-values': true,
    'time-min-milliseconds': 100,
    // 'unit-allowed-list': [],
    // 'unit-disallowed-list': [],
    'value-no-vendor-prefix': true,

    // ----- Stylistic Issues --------------------------------------------------
    /* eslint-disable sonarjs/no-duplicate-string */
    'at-rule-name-newline-after': 'always-multi-line',
    'at-rule-semicolon-space-before': 'never',
    // 'block-closing-brace-space-after': 'always',
    // 'block-opening-brace-newline-before': 'always',
    'declaration-block-semicolon-newline-before': 'never-multi-line',
    // 'font-family-name-quotes': 'always-where-recommended',
    'function-comma-newline-before': 'never-multi-line',
    'function-url-quotes': 'never',
    'max-line-length': 120,
    'media-query-list-comma-newline-before': 'never-multi-line',
    'no-empty-first-line': true,
    'selector-attribute-quotes': 'always',
    'selector-list-comma-newline-before': 'never-multi-line',
    'selector-list-comma-space-after': 'always-single-line',
    'string-quotes': 'single',
    'value-list-comma-newline-before': 'never-multi-line',
    linebreaks: 'unix',
    /* eslint-enable sonarjs/no-duplicate-string */

    // ----- Plugins -----------------------------------------------------------
    'csstools/use-nesting': 'always',
    'order/properties-alphabetical-order': true,
    'plugin/declaration-block-no-ignored-properties': true,
  },
}
